name: Main Workflow
on:
  push:
    branches: ['**']

jobs:
  assist:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Git
        uses: actions4git/setup-git@v1

      - name: Install dependencies
        run: |
          bun install

      - name: Run lint
        run: |
          bun lint

      - name: Run tests
        run: |
          bun test